apiVersion: v1
kind: Pod
metadata:
  name: tcp-state-pod
  namespace: ddosify
spec:
  containers:
  - name: tcp-state
    image: tcp-state:v8
    securityContext:
      privileged: true
      runAsUser: 0
      capabilities:
        add:
          - BPF
          - PERFMON
          - NET_ADMIN
          - SYS_RESOURCE
    volumeMounts:
      - mountPath: /sys/kernel/debug
        name: debugfs
        readOnly: false
      - mountPath: /var/run/containerd/containerd.sock
        name: containerd-sock
        readOnly: true
  volumes:
    - name: debugfs
      hostPath:
        path: /sys/kernel/debug
    - hostPath:
          path: /var/run/containerd/containerd.sock
      name: containerd-sock
