---
# For alaz to keep track of changes in cluster, TODO: ServiceAccount must be different
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: alaz-role
  namespace: ddosify
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alaz-role-binding
  namespace: ddosify
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: alaz-role
subjects:
- kind: ServiceAccount
  name: alaz-serviceaccount
  namespace: ddosify
