apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alaz-daemonset
  namespace: ddosify
spec:
  selector:
    matchLabels:
      app: alaz
  template:
    metadata:
      labels:
        app: alaz
    spec:
      serviceAccount: alaz-serviceaccount                                                                                                              │
      serviceAccountName: alaz-serviceaccount
      containers:
      - name: alaz-pod
        image: 158138719754.dkr.ecr.eu-central-2.amazonaws.com/alaz:v3.8.6
        env:
          - name: K8S_COLLECTOR_ENABLED
            value: "true"
          - name: CR_COLLECTOR_ENABLED
            value: "true"
          - name: EBPF_ENABLED
            value: "true"
          - name: IN_CLUSTER
            value: "true"
          - name: POSTGRES_HOST
            value: "postgres-service.ddosify"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_USER
            value: "alazuser"
          - name: POSTGRES_PASSWORD
            value: "alazpwd"
          - name: POSTGRES_DB
            value: "alazdb"
          - name: LOG_LEVEL
            value: "0"
          - name: DISABLE_LOGS
            value: "false"
          - name: DS_PG
            value: "true"
          - name: DS_BACKEND
            value: "false"
          - name: BACKEND_HOST
            value: https://staging-backend-cf.ddosify.com
          - name: BACKEND_PORT
            value: "443"
          - name: MONITORING_ID
            value: 421686fb-26a5-43e6-8b3c-b1e06ea39603
        ports:
          - containerPort: 8181
        securityContext:
          capabilities:
            add:
              - BPF
              - PERFMON
              - NET_ADMIN
              - SYS_RESOURCE
        volumeMounts:
          - mountPath: /sys/kernel/debug
            name: debugfs
            readOnly: false
          - mountPath: /var/run/containerd/containerd.sock
            name: containerd-sock
            readOnly: true
      volumes:
        - name: debugfs
          hostPath:
            path: /sys/kernel/debug
        - name: containerd-sock
          hostPath:
            path: /var/run/containerd/containerd.sock
