apiVersion: v1
kind: ServiceAccount
metadata:
  name: alaz-serviceaccount
  namespace: anteon
---
# For alaz to keep track of changes in cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alaz-role
  namespace: anteon
rules:
- apiGroups:
  - "*"
  resources:
  - pods
  - services
  - endpoints
  - replicasets
  - deployments
  - daemonsets
  - statefulsets
  verbs:
  - "get"
  - "list"
  - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alaz-role-binding
  namespace: anteon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alaz-role
subjects:
- kind: ServiceAccount
  name: alaz-serviceaccount
  namespace: anteon
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alaz-daemonset
  namespace: anteon
spec:
  selector:
    matchLabels:
      app: alaz
  template:
    metadata:
      labels:
        app: alaz
    spec:
      hostPID: true
      containers:
      - env:
        - name: TRACING_ENABLED
          value: "true"
        - name: METRICS_ENABLED
          value: "true"
        - name: LOGS_ENABLED
          value: "true"
        - name: BACKEND_HOST
          value: https://api-alaz.getanteon.com:443
        - name: LOG_LEVEL
          value: "1"
        # - name: EXCLUDE_NAMESPACES
        #   value: "^anteon.*"
        - name: MONITORING_ID
          value: <MONITORING_ID>
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        args:
        - --no-collector.wifi
        - --no-collector.hwmon
        - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)
        - --collector.netclass.ignored-devices=^(veth.*)$
        image: ddosify/alaz:v0.11.0
        imagePullPolicy: IfNotPresent
        name: alaz-pod        
        ports:
        - containerPort: 8181
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 400Mi
        securityContext:
          privileged: true 
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        # needed for linking ebpf trace programs
        volumeMounts:
        - mountPath: /sys/kernel/debug
          name: debugfs
          readOnly: false  
        # self-signed cert will be used
        - name: ca-cert
          mountPath: "/tmp/anteon-ca-cert"
          readOnly: true   
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: alaz-serviceaccount
      serviceAccountName: alaz-serviceaccount
      terminationGracePeriodSeconds: 30
      # needed for linking ebpf trace programs
      volumes:
      - name: debugfs
        hostPath:
          path: /sys/kernel/debug
      # self-signed cert will be used
      - name: ca-cert
        secret:
          secretName: anteon-ca
---
apiVersion: v1
data:
  # // cat ca.crt | base64
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZQRENDQXlTZ0F3SUJBZ0lVUlIzOFBMRGFFakVlVU9Bc1NpT1U5ZG5sNFBrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dERVdNQlFHQTFVRUF3d05aMlYwWVc1MFpXOXVMbU52YlRBZUZ3MHlOREEwTVRBeU1EQTVNalZhRncwegpOREEwTURneU1EQTVNalZhTUJneEZqQVVCZ05WQkFNTURXZGxkR0Z1ZEdWdmJpNWpiMjB3Z2dJaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUUNvZjhaRmFpdzZzQm0ybVpoeVpuakR2dmxMakNJd3p3MW0KWmZwTWt5eUx5aENheGNSM0hVNk9SeDdJWmV4R2VqSDYxSTlhMlZUZmlDRER0UWNORkJtdTM2ME4yVTBsN1k4Vgp4NTBtT2xuV1JPUEhLaFpBV01QTnV2d2VUYnJmUWl3SVAvNEpGaTRzM3p6LzduV09CeXlPVmoxTlRETzdrZ0s0Cjd2dGNJUkhGQTVQM1MyQ2FCYkVrOHg3RzdvZjNCTlF1cDhyK2FGaWNaQlZwa2VXZFhTVnNQSSs0ZElDL1RKczIKdWhPNzNNTzdPSE1aQmg0ak5ha3hrNmhMYWRMTWtSZlJ1YTc3NjFDd1hBWkM1MWVKZkhIYThYVWZob0ZSMzh5YgpIZlYrQXVZV1N5Y2R4d3ZtaHFaOWk4ZXpoNEpEQjZrMko5MXM1ck42UXdjYjFqYkVkWTR5bW9kSnlGOTNlZHBjCnB0MjBoOEtENkVDVjdlK0R1OC9Wd3I5UHNSb2tFb05yaEMwNVNqZC9tQTFJY0JQMEdJdUdSRWhqblRGelRsb3oKa0d2YUU3a0h2aGVQalZrUkIxTDU3RG13dDFuN1YvMHN0Qm9hOWhPL3pmVzVFbGdFM242K1RKc3VWaWNzQjJ2LwpmcnZQRllrQjl4Q0ZHalVMVi9BMUVUS2dYdEFJTXhXemxsTk1obmFJVlFLbU0xa0tHTVhrdG8xMU9IUnlrSFBFCnFyU3U0UXc2OWh5Sk9jVXA3OTUzWFFKMVFiY05ROUVicFI4WXd2QzMvVUJxMzVZNEZxSlZlSlN4Nk5uVnN0bzIKaWUvaWRFTURCbCswZHJYbVRmRnEzKzJsYStka3haTHo1d1MxOHE1emdKSUtMQ3dCUVZPR29KbUJXaXRRUGd6YgpUNFM2cUNJaUJ3SURBUUFCbzM0d2ZEQWRCZ05WSFE0RUZnUVUvaUh4QzFnbG01U0c3TTNaaWxwY0E1d2k0RDh3Ckh3WURWUjBqQkJnd0ZvQVUvaUh4QzFnbG01U0c3TTNaaWxwY0E1d2k0RDh3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBcEJnTlZIUkVFSWpBZ2dnMW5aWFJoYm5SbGIyNHVZMjl0Z2c4cUxtZGxkR0Z1ZEdWdmJpNWpiMjB3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFKTm5hV2c0eWNCekhuKzlUSFNnd3h0WWVUYUt6djFHV1IyZzVwalFNVmc4CkNwTVpXQlVxNUw4cGw0dHQ5TDlpcUlGZ3FhT3gvZzJqZUtrV08xaUhsdXpSdkFKVVJZdWZ4Y2l4bnFpcTVsQmwKTVMwNDVpbDVGaHhndW15MERhVlBibEVsZktuMlRDYVZKRWhickhXZVBUSmpFcmhoN21tNFBNc1ZRTXgzUzVMcQpCWXhMRXM3ZHNWbGQvblI1cFl5dUlVWEY2S1pwb0pLVzYwbTEyT3hpV1BTNHJTOVBGN0d6VXpyTm9KQWRGWWtpCktnR3FSRjA5TlNkRzRqTkFSK2FJVVNHdkFzTjZUMW5tVnVDTVZkUkJxTUxiMTlyUHNzdzMwV0dSemtZaXhZSG4KbkZkeUtRTXM1QWFLZ2M4b3ZSdWJGSWhHVlE2YlZ0VXNlTW9aZ29vdUg4RVNiRWIwa1h2cjdvS0U3U1FZWEQvVwo2c1BLelZyZlViQ0VBYStvSnRCMEhpWlFkOHdmczBURGROanZVUkNFSExYdnNmVnVDQlF4RjVsbWJ4R3Fmdm1jCjJrTEJHZiszckFXSWkrZUNuSW1oTU1VWXNDV1pHMXBlRHNLUXpYV2hCUlg4VE5kQTlYUTI0RUJ1VVlWRVZiNUgKSzJ2V24rUHkrem1qN2NzbEFwNmZ1QmJJSkVFZldCeld6S0RSa0VjaUpGZDhmRk5WSFZUOUx1azQvdGZjc0VuTQpHR2l0R1dRSVBaRGZwZEw2ZmYyZ3VyZjZDRTkxb3IzNjhhaDFIZDBoVThnMnQ0eG5FUU9HLzRDWFBDa3R5L3NTCllrZXhnWGVxV1RaMDRVUC9CSHNxd1dlUVFyZW9jdXhjLzRKejRZUThiN1Aya1JJZWhqVmRVamdkYU15OUpETE4KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  tls.key: # empty
kind: Secret
metadata:
  name: anteon-ca
  namespace: anteon
type: kubernetes.io/tls
