apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alaz-daemonset
  namespace: ddosify
spec:
  selector:
    matchLabels:
      app: alaz
  template:
    metadata:
      labels:
        app: alaz
    spec:
      serviceAccount: alaz-serviceaccount                                                                                                              │
      serviceAccountName: alaz-serviceaccount
      containers:
      - name: alaz
        image: 158138719754.dkr.ecr.eu-central-2.amazonaws.com/alaz:v1.5
        env:
          - name: K8S_COLLECTOR_ENABLED
            value: "true"
          - name: CR_COLLECTOR_ENABLED
            value: "false"
          - name: EBPF_ENABLED
            value: "true"
          - name: IN_CLUSTER
            value: "true"
          // TODO: configs for postgres of selfhosted
          - name: POSTGRES_HOST
            value: ""
          - name: POSTGRES_PORT
            value: ""
          - name: POSTGRES_USER
            value: ""
          - name: POSTGRES_PASSWORD
            value: ""
          - name: POSTGRES_DB
            value: ""
        ports:
          - containerPort: 8181
        securityContext:
          # privileged: true
          # runAsUser: 0
          capabilities:
            add:
              - BPF
              - PERFMON
              - NET_ADMIN
              - SYS_RESOURCE
        volumeMounts:
          - mountPath: /sys/kernel/debug
            name: debugfs
            readOnly: false
          - mountPath: /var/run/containerd/containerd.sock
            name: containerd-sock
            readOnly: true
      volumes:
        - name: debugfs
          hostPath:
            path: /sys/kernel/debug
        - name: containerd-sock
          hostPath:
            path: /var/run/containerd/containerd.sock
