apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"10"},"creationTimestamp":"2023-07-21T09:56:21Z","generation":10,"labels":{"app":"prometheus-server"},"name":"prometheus-deployment","namespace":"monitoring","resourceVersion":"17984058","uid":"e2dffcfa-4140-4bec-92c6-aaf4be147af4"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"prometheus-server"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2023-07-25T15:40:45+03:00"},"creationTimestamp":null,"labels":{"app":"prometheus-server"}},"spec":{"containers":[{"args":["--config.file=/etc/prometheus/prometheus.yml","--storage.tsdb.path=/prometheus/"],"image":"prom/prometheus","imagePullPolicy":"Always","name":"prometheus","ports":[{"containerPort":9090,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/etc/prometheus/","name":"prometheus-config-volume"},{"mountPath":"/prometheus/","name":"prometheus-storage-volume"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"configMap":{"defaultMode":420,"name":"prometheus-server-conf"},"name":"prometheus-config-volume"},{"emptyDir":{},"name":"prometheus-storage-volume"}]}}},"status":{"conditions":[{"lastTransitionTime":"2023-07-25T12:31:23Z","lastUpdateTime":"2023-07-25T12:31:23Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"},{"lastTransitionTime":"2023-07-21T09:56:21Z","lastUpdateTime":"2023-07-25T12:40:45Z","message":"ReplicaSet \"prometheus-deployment-66cc7f9b5c\" is progressing.","reason":"ReplicaSetUpdated","status":"True","type":"Progressing"}],"observedGeneration":10,"replicas":2,"unavailableReplicas":2,"updatedReplicas":1}}
  creationTimestamp: "2023-07-25T12:41:12Z"
  generation: 3
  labels:
    app: prometheus-server
  name: prometheus-deployment
  namespace: monitoring
  resourceVersion: "17984776"
  uid: 9173af76-9460-4380-a9c0-24335e1e7f73
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-07-25T15:43:25+03:00"
      creationTimestamp: null
      labels:
        app: prometheus-server
    spec:
      containers:
      - args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus/
        image: prom/prometheus
        imagePullPolicy: Always
        name: prometheus
        ports:
        - containerPort: 9090
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus/
          name: prometheus-config-volume
        - mountPath: /prometheus/
          name: prometheus-storage-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: prometheus-server-conf
        name: prometheus-config-volume
      - emptyDir: {}
        name: prometheus-storage-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-07-25T12:42:49Z"
    lastUpdateTime: "2023-07-25T12:42:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-07-25T12:41:12Z"
    lastUpdateTime: "2023-07-25T12:43:28Z"
    message: ReplicaSet "prometheus-deployment-64b787c8cd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
